---
- name: configure application servers
  hosts: app
  become: yes
  #serial: 1

  vars:
    nginx_port: 80

  tasks:
    - name: install cowsay
      yum:
        name: cowsay
        state: present

    - name: create deploy user
      user:
        name: deploy
        state: present
        create_home: yes

    - name: install nginx
      yum: name=nginx state=present

    - name: configure nginx
      template: src=nginx.conf.j2 dest=/tmp/example.conf

- name: deploy irc server
  hosts: irc

  vars:
    url: https://github.com/ergochat/ergo/releases/download/v2.9.1/ergo-2.9.1-linux-x86_64.tar.gz

  tasks:

    - name: install cowsay
      yum: name=cowsay state=present
      become: yes
    
    - name: create ergo user
      user: name=ergo shell=/bin/bash create_home=yes
      become: yes

    - name: download ergochat v2.9.1
      get_url:
        url: "{{ url }}"
        dest: /tmp/irc.tgz

    - name: extract ergochat
      unarchive: src=/tmp/irc.tgz dest=/tmp/ remote_src=yes

    - name: copy ergo configuration
      template: src=ircd.yaml.j2 dest=/tmp/ergo-2.9.1-linux-x86_64/ircd.yaml
    
    
