---
# tasks file for ergo

- name: create ergo user
  user: name=ergo shell=/bin/bash create_home=yes
  become: yes

- name: download ergochat v2.9.1
  get_url:
    url: "{{ url }}"
    dest: /tmp/irc.tgz

- name: extract ergochat
  unarchive: src=/tmp/irc.tgz dest=/tmp/ remote_src=yes

- name: copy ergo configuration
  template: src=ircd.yaml.j2 dest=/tmp/ergo-2.9.1-linux-x86_64/ircd.yaml
